return {
	-- {
	--   "zbirenbaum/copilot.lua",
	--   cmd = "Copilot",
	--   event = "InsertEnter",
	--   config = function()
	--     require("copilot").setup({})
	--   end,
	-- },
	-- {
	--   "zbirenbaum/copilot-cmp",
	--   config = function()
	--     require("copilot_cmp").setup({})
	--   end,
	-- },
	-- {
	--   "CopilotC-Nvim/CopilotChat.nvim",
	--   branch = "canary",
	--   dependencies = {
	--     { "github/copilot.vim" }, -- or github/copilot.vim
	--     { "nvim-lua/plenary.nvim" }, -- for curl, log wrapper
	--   },
	--   opts = {
	--     debug = true, -- Enable debugging
	--     mappings = {
	--       reset = {
	--         normal ='',
	--         insert = '<C-l>'
	--       },
	--     }
	--   },
	--   -- See Commands section for default commands if you want to lazy load on them
	-- },
}
